---
format_version: '11'
default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
project_type: other
trigger_map:
  - push_branch: dev
    pipeline: dev
  - pull_request_target_branch: dev
    pull_request_source_branch: '*'
    pipeline: dev

pipelines:
  dev:
    stages:
      - main: {}

stages:
  main:
    workflows:
      - build: {}
      - test: {}

workflows:
  build:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@6: { }
      - script@1:
          inputs:
            - content: |-
                #!/usr/bin/env bash
                # fail if any commands fails
                set -e
                set -o pipefail
                set -x
                docker version
                docker build -f kem-api-go/Dockerfile kem-api-go/

      - deploy-to-bitrise-io@2: {}
  test:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@6: { }
      - script@1:
          title: Do anything with Script step
          inputs:
            - content: |-
                #!/usr/bin/env bash
                set -e
                set -o pipefail
                set -x
                docker version
                # Test app
                docker build -f kem-api-go/unit-test.dockerfile -t kem-api-go-unit-test:latest  kem-api-go/
                docker run kem-api-go-unit-test:latest

      - deploy-to-bitrise-io@2: { }


meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: standard
