package repository

import (
	"github.com/morbalint/kem-api-go/dtos"
)

var Characters = []dtos.Character{
	{
		Name:           "Helmar",
		Class:          "Íjász - 9, Tolvaj - 2",
		Level:          11,
		Race:           "Elf",
		Alignment:      "Kaotikus jó",
		Gender:         "Férfi",
		AgeInYears:     34,
		Religion:       "Istár",
		Strength:       15,
		Dexterity:      16,
		Constitution:   13,
		Intelligence:   13,
		Wisdom:         11,
		Charisma:       10,
		Endurance:      6,
		ReflexBase:     6,
		WillPowerBase:  3,
		HPMax:          96,
		HPCurrent:      96,
		ACArmor:        6,
		ACShield:       2,
		ACOther:        1,
		Initiative:     6,
		MovementInFeet: 20,
	},
	{
		Name:           "Ayla",
		Class:          "Papnő",
		Level:          11,
		Race:           "Ember",
		Alignment:      "Semleges jó",
		Gender:         "Nő",
		AgeInYears:     29,
		Religion:       "Istár",
		Strength:       12,
		Dexterity:      12,
		Constitution:   15,
		Intelligence:   15,
		Wisdom:         17,
		Charisma:       16,
		Endurance:      7,
		ReflexBase:     3,
		WillPowerBase:  7,
		HPMax:          80,
		HPCurrent:      80,
		ACArmor:        11,
		ACShield:       5,
		ACOther:        1,
		Initiative:     1,
		MovementInFeet: 20,
	},
}
